version: '3'
services:
  app:
    image: golang:latest
    volumes:
      - $PWD:/go/src/example.com/go-http-demo
    ports:
      - "8000:5000"
    command: bash -c "cd /go/src/example.com/go-http-demo && go run main.go"